### ISSUE TITLE
Імпрувнути exception handling для ConstaintViolationException

### ISSUE THREAD

**Issue by ivanursul** [ifnul/ums-backend#10]
Існуючі exception хендлери містятьс в 
..../ums-backend/is-lnu-rest-api/src/main/java/org/lnu/is/web/rest/handler

Потрібно написати аналогічний хендлер, який би витягував адекватний меседж, і показував нормально повідомлення користувачу.
Зараз меседж такий:

{
"messageType": "ERROR",
"message": "Request processing failed; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement",
"httpCode": 500
}

Потрібно щось в такому роді(просто приклад)

{
"messageType": "ERROR",
"message": "ConstaintViolationName: message",
"httpCode": 500
}

**Comment by moro-programmer** [comment]
додав в PersistenceExceptionHandler
